LearningLog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'',include('LearningLogs.urls',namespace='LearningLogs')),
]

LearningLogs/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^topics/$',views.topics,name='topics'),
    url(r'^topic/(?P<topic_slug>\w+)/$',views.topic,name='topic'),
    url(r'^new_topic/$',views.new_topic,name="new_topic"),
    url(r'^new_entry/(?P<topic_slug>\w+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),
    url(r'^public_entries/(?P<topic_slug>\w+)/$', views.public_topics, name='public_entries'),
    url(r'^new_comment/(?P<entry_id>\d+)/$',views.new_comment, name='new_comment')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login


from . import views

urlpatterns = [
    # Login page.
    url(r'^login/$', login, {'template_name': 'users/login.html'},name='login'),
    url(r'^logout/$', views.logout_view,name='logout'),
    url(r'^register/$', views.register, name='register'),
    ]

LearningLogs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    slug = models.SlugField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.text)
        super(Topic, self).save(*args, **kwargs)




    def __unicode__(self):
        return self.text


class Comments(models.Model):
    owner = models.ForeignKey(User)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    entry = models.ForeignKey("LearningLogs.Entry")

    class Meta:
        ordering = ['-date_added']

    def __unicode__(self):
        return self.text




class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'entries'

    def __unicode__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

LearningLogs/forms.py
from django import forms
from .models import Topic, Entry, Comments

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    public = forms.BooleanField(required=False)
    class Meta:

        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text',]
        labels = {'text': 'Write your comment'}

LearningLogs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect , Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


from .models import Topic, Entry, Comments
from .forms import TopicForm, EntryForm, CommentForm


# Create your views here.

def index(request):
    entries =  Entry.objects.all().filter(public=True).order_by('-date_added')
    topics = Topic.objects.all()
    context = {'entries': entries, 'topics': topics}
    return render(request,"LearningLogs/index.html", context)

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {'topics':topics}
    return render(request,'LearningLogs/topics.html',context)


@login_required
def topic(request, topic_slug):
    topic = Topic.objects.get(slug=topic_slug)
    check_topic_owner(request, topic)
    entries = topic.entry_set.order_by('-date_added')


    context = {'topic': topic, 'entries': entries}
    return render(request, 'LearningLogs/topic.html', context)


@login_required
def new_topic(request):
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            form.save()
            return HttpResponseRedirect(reverse("LearningLogs:topics"))
    context = {'form':form}
    return render(request,'LearningLogs/new_topic.html',context)


@login_required
def new_entry(request, topic_slug):
    topic = Topic.objects.get(slug=topic_slug)
    check_topic_owner(request, topic)


    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()

            return HttpResponseRedirect(reverse('LearningLogs:topic',
                                                args=[topic.slug]))

    context = {'topic': topic, 'form': form}
    return render(request, 'LearningLogs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)
    public = entry.public
    if request.method != "POST":
        form = EntryForm(instance=entry, initial={"public" : public})
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            edit_entry = form.save(commit=False)
            if request.POST.get("public"):
               edit_entry.public = True
            else:
                edit_entry.public = False
            edit_entry.save()
            return HttpResponseRedirect(reverse('LearningLogs:topic', args=[topic.slug]))
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'LearningLogs/edit_entry.html',context)

def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404

def public_topics(request, topic_slug):
    entries = Entry.objects.all().filter(public=True,topic__slug=topic_slug).order_by('-date_added')
    comments = Comments.objects.filter(entry__topic__slug=topic_slug)
    context = {"entries": entries, "comments": comments}
    return render(request, 'LearningLogs/public_entries.html', context)

def new_comment(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.entry = entry
            new_comment.owner = request.user
            new_comment.save()
        return HttpResponseRedirect(reverse('LearningLogs:topics'))
    context =  {"entry":entry, "form":form}
    return render(request,'LearningLogs/new_comment.html',context)

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('LearningLogs:index'))


def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('LearningLogs:index'))
    context = {'form': form}
    return render(request,'users/register.html',context)

templates/LearningLogs/base.html
{% load bootstrap3 %}
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script type="text/javascript" src="{% static 'jquery-3.2.1.js' %}"></script>




</head>

<body>
<!--Static navbar-->

<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"></button>
            <a class="navbar-brand" href="{% url 'LearningLogs:index' %}">Learning Logs</a>


        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                   <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">Topics
         <span class="caret"></span></a>
         <ul class="dropdown-menu">

         {%if user.is_authenticated %}
              <li><a href="{% url 'LearningLogs:topics' %}">My topics</a></li>
             <li><a href="{% url 'LearningLogs:new_topic' %}">Add Topic</a></li>
             <li role="separator" class="divider"></li>
         {% for topic in MenuTopics %}
         <li><a href="{% url "LearningLogs:topic" topic.slug %}">{{ topic }}</a></li>
             {% endfor %}
             {% else %}
              <li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-user"></span> register</a> </li>
                <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> log in</a> </li>
             {% endif %}
         <li role="separator" class="divider"></li>
         <li class="dropdown-header">Publicated topics </li>
          {% for publicTopic in publicTopics %}
              {% if publicTopic.topic.owner != user %}
              <li><a href="{% url "LearningLogs:public_entries" publicTopic.topic.slug %}">{{ publicTopic.topic }}</a> </li>
{% endif %}
    {% endfor %}

         </ul>
                     </li>









                 {%if user.is_authenticated %}






                     <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">New Entry
         <span class="caret"></span></a>
         <ul class="dropdown-menu">
         {% for topic in MenuTopics %}
         <li><a href="{% url "LearningLogs:new_entry" topic.slug %}">{{ topic }}</a></li>
             {% endfor %}
         </ul>
                     </li>
            {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}</a></li>
                <li><a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span> log out</a> </li>
                {% else %}
                <li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-user"></span> register</a> </li>
                <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> log in</a> </li>
                {% endif %}
            </ul>


        </div>
        <!--/.nav-collapse-->
    </div>
</nav>

<div class="container">
    <div class="page-header">
    {% block header %}{% endblock header %}

        {% block content %}{% endblock content %}

    </div>
</div>

</body>

</html>

templates/LearningLogs/edit_entry.html
{% extends "LearningLogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2> <a href="{% url 'LearningLogs:topic' topic.slug %}">{{ topic }}</a> </h2>
<p>Edit Entry:</p>
{% endblock header %}

{% block content %}
<form action="{% url 'LearningLogs:edit_entry' entry.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">Save Changes</button>
    {% endbuttons %}

</form>

{% endblock content %}

templates/LearningLogs/index.html
{% extends "LearningLogs/base.html" %}

{% block header %}
    <div class="jumbotron">
    <h1>Track your learning</h1>
    </div>
{% endblock header %}



{% block content %}
    <script type="text/javascript">
    socket = new WebSocket('ws://' + window.location.host + "/index/");
    socket.onopen = function () {
        socket.send('{{ user.username }}');
    };

          socket.onmessage = function (msg) {
        $('#test').text(msg.data);

          };
    </script>





    <h2>
    {%if user.is_authenticated %}
        Welcome, {{ user.username }} make new topics, and edit your entries
    {% else %}
        <a href="{% url 'users:register' %}">Register an account</a> to make your own Log.
    {% endif %}
    </h2>
    <p> This is entries that have been made public</p>




         {% for topic in publicTopics %}
             <div class="panel panel-primary">
             <div class="panel-heading">
                 <div class="panel-title"><a data-toggle="collapse" href="#{{ topic.topic }}">{{ topic.topic }}  <h6>with {{ topic.topic.entry_set.all.count }} public entries</h6></a>

                 </div>

             </div>
             <div id="{{ topic.topic }}" class="panel-collapse collapse">
             <div class="panel-body">
                 {% for entry in entries %}
                     {% if entry.topic == topic.topic %}
                      <div class="panel panel-primary">
                      <div class="panel-heading">
                          <h6 class="panel-title"><small>{{ entry.date_added }}</small> </h6>
                      </div>
                          <div class="panel-body">
                          {{ entry.text }}

                      </div>

                      {% if entry.comments_set.count > 0 %}
    <div class="panel-footer">
    <a data-toggle="collapse" href="#{{ entry.id }}">{{  entry.comments_set.count }} comments</a>
    <div id="{{ entry.id }}" class="panel-collapse collapse">
        {% for comment in entry.comments_set.all %}
                <div class="panel panel-info">
                <div class="panel-heading">
                <h6>Commented by {{ comment.owner }}  <small>on {{ comment.date_added }}</small> </h6>
                </div>
                <div class="panel-body">
              <h5>{{ comment.text }}</h5>
                </div>
                </div>


              {% endfor %}
    </div>
    </div>
    {% endif %}


                      </div>
                     {% endif %}
                     {% endfor %}
             </div>

             </div>
             </div>
      {% endfor %}



    <h6>Chat with other users  <div id="test"></div> </h6>





{% endblock content %}

templates/LearningLogs/new_comment.html
{% extends "LearningLogs/base.html" %}
{% load bootstrap3 %}
{% block header %}

    <div class="panel panel-primary">

    <div class="panel-heading">
        {{ entry.topic }}
    </div>
        <div class="panel-body">
            {{ entry }}


        </div>
    </div>

{% endblock header %}

{% block content %}


  <form action="{% url 'LearningLogs:new_comment' entry.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name='submit' class="btn btn-primary">Add comment</button>
  {% endbuttons %}
  </form>

{% endblock content %}

templates/LearningLogs/new_entry.html
{% extends "LearningLogs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h3>
    <a href="{% url 'LearningLogs:topic' topic.slug %}">{{ topic }}</a>
    <small>Add a new entry:</small>
</h3>
{% endblock header %}

{% block content %}
  <form action="{% url 'LearningLogs:new_entry' topic.slug %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name='submit' class="btn btn-primary">add entry</button>
  {% endbuttons %}
  </form>

{% endblock content %}

templates/LearningLogs/new_topic.html
{% extends 'LearningLogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>Add a new topic</h2>
{% endblock header %}

{% block content %}


<form action="{% url 'LearningLogs:new_topic' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="Submit" class="btn btn-primary">Add Topic</button>
    {% endbuttons %}

</form>

{% endblock content %}

templates/LearningLogs/public_entries.html
{% extends "LearningLogs/base.html" %}

{% block header %}



{% endblock header %}





{% block content %}


{% for entry in entries %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3>{{ entry.topic}} by {{ entry.topic.owner }}    </h3>

            <h6>
               {{ entry.date_added }}

            </h6>

        </div>
        <div class="panel-body">
            {{ entry.text}}
            <h6><a href="{% url 'LearningLogs:new_comment' entry.id %}">Add Comment</a> </h6>
        </div>
    {% if entry.comments_set.count > 0 %}

    <div class="panel-footer">
     <a data-toggle="collapse" href="#{{ entry.id }}">{{ entry.comments_set.count }} Comments</a>
    <div id="{{ entry.id }}" class="panel-collapse collapse">


        {% for comment in entry.comments_set.all %}
            {% if comment.entry == entry %}
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h6>Commented by {{ comment.owner }}  <small>on {{ comment.date_added }}</small> </h6>
                    </div>
    <div class="panel-body">
{{ comment }}
    </div>
</div>
    {% endif %}
        {% endfor %}
    </div>
    </div>
    {% endif %}



</div>

                {% endfor %}

{% endblock content %}

templates/LearningLogs/topic.html
{% extends 'LearningLogs/base.html' %}

{% block header %}
<h2><a href="{% url 'LearningLogs:topics' %}">Topics - </a>{{ topic }}</h2>
{% endblock header %}

{% block content %}

  <p>
    <a href="{% url 'LearningLogs:new_entry' topic.slug %}">add new entry</a>
  </p>


    {% for entry in entries %}
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
          <h5><small>
          <a href="{% url 'LearningLogs:edit_entry' entry.id %}" >Edit entry</a>
          </small> </h5>
      </div>

     {% if entry.comments_set.count > 0 %}
    <div class="panel-footer">
    <a data-toggle="collapse" href="#{{ entry.id }}">{{  entry.comments_set.count }} comments</a>
    <div id="{{ entry.id }}" class="panel-collapse collapse">
        {% for comment in entry.comments_set.all %}
                <div class="panel panel-info">
                <div class="panel-heading">
                <h6>Commented by {{ comment.owner }}  <small>on {{ comment.date_added }}</small> </h6>
                </div>
                <div class="panel-body">
              <h5>{{ comment.text }}</h5>
                </div>
                </div>


              {% endfor %}
    </div>
    </div>
    {% endif %}





        </div>
  {% empty %}
      There are no entries for this topic yet.


  {% endfor %}




{% endblock content %}

templates/LearningLogs/topics.html
{% extends "LearningLogs/base.html" %}

{% block header %}
<h1>Topics</h1>
{% endblock header %}



{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <h3>
            <a href="{% url 'LearningLogs:topic' topic.slug %}">{{ topic }}</a>
        </h3>
	  </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'LearningLogs:new_topic' %}">Add new topic</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "LearningLogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Log in to your account</h2>
<ul> Or <a href="{% url 'users:register' %}">Register</a> an account </ul>
{% endblock header %}

{% block content %}


<form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'LearningLogs:index' %}">
</form>

{% endblock content %}

users/templates/users/register.html
{% extends 'LearningLogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h3>Make new account</h3>
{% endblock header %}

{% block content %}

<form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'LearningLogs:index' %}"/>
</form>

{% endblock content %}